### PR TITLE
Map site refactored

### PR DESCRIPTION
**Pull request by todvora**
Hi, 
I refactored the map site little bit. Here are some advantages of the current solution:

- Async data requests (without the warning `Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience.`)
- No code duplication in every language mutation, only one shared js file
- Localization in one place, could be replaced by an [integration with POEditor later](https://github.com/integrations/poeditor)
- Switching cities doesn't reload the whole page, does only one ajax req. (2-3x faster, saves data) 

There is a demo running on https://todvora.github.io/parkendd.de/map.html

Please give it a try and let me know what you think about it. 

Thanks,
Tomas

### CODE REVIEW

**Comment by Mic92** [comment]
Thanks for your effort! Changes looks good to me and are an overall improvement.

**Comment by todvora** [comment]
Thanks for the merge @Mic92!

**Comment by jklmnn** [comment]
Thanks for the work @todvora !
I have added some minor fixes to also make it work on the start page (we use the same map there).

**Comment by todvora** [comment]
Hi @jklmnn,
Thanks for the fix and sorry that I missed that. I thought that the map on home page is a screenshot :-)

**Comment by jklmnn** [comment]
No problem. It's a live map, but with some features disabled (e.g. scrolling) because it shouldn't interfere with the normal usage of the page.

**Pull request merged**
